'use client'

import { useAuth } from '@/contexts/AuthContext'
import { Button } from '@/components/ui/Button'
import { LoadingSpinner } from '@/components/loading'
import Link from 'next/link'
import { Brain, TrendingUp, Users, Dumbbell, Apple, Heart } from 'lucide-react'

export default function HomePage() {
  const { user, profile, loading, signOut } = useAuth()

  if (loading) {
    // Simple centered spinner since we don't know which layout to show yet
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <LoadingSpinner size="lg" className="text-primary mb-4" />
          <p className="text-muted-foreground">Loading Flexora...</p>
        </div>
      </div>
    )
  }

  if (!user) {
    // Landing page for unauthenticated users
    return (
      <div className="min-h-screen bg-background">
        {/* Header Navigation */}
        <header className="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container mx-auto px-4 py-4 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Dumbbell className="h-8 w-8 text-primary" />
              <h1 className="text-2xl font-bold">Flexora</h1>
            </div>
            <div className="flex items-center gap-4">
              <Link href="/auth">
                <Button variant="ghost">Sign In</Button>
              </Link>
              <Link href="/auth">
                <Button>Get Started</Button>
              </Link>
            </div>
          </div>
        </header>

        {/* Hero Section */}
        <div className="container mx-auto px-4 py-20">
          <div className="text-center max-w-4xl mx-auto">
            <div className="inline-flex items-center gap-2 mb-6 px-3 py-1 rounded-full border bg-muted/50">
              <Heart className="h-4 w-4 text-primary" />
              <span className="text-sm font-medium">Your AI-Powered Fitness Companion</span>
            </div>
            
            <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-6">
              Transform Your
              <span className="bg-gradient-to-r from-indigo-600 via-emerald-600 to-amber-600 bg-clip-text text-transparent"> Fitness Journey</span>
            </h1>
            
            <p className="text-xl text-muted-foreground mb-10 max-w-2xl mx-auto leading-relaxed">
              Get personalized workout and nutrition plans powered by AI. Track your progress, 
              connect with trainers, and achieve your goals faster than ever.
            </p>
            
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link href="/auth">
                <Button size="lg" className="text-lg px-8 py-6">
                  Start Your Journey
                  <Dumbbell className="ml-2 h-5 w-5" />
                </Button>
              </Link>
              <Link href="/auth">
                <Button variant="outline" size="lg" className="text-lg px-8 py-6">
                  Sign In
                </Button>
              </Link>
            </div>
          </div>
        </div>

        {/* Features Section */}
        <div className="container mx-auto px-4 py-20">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Everything You Need to Succeed</h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Powerful features designed to help you reach your fitness goals faster and more efficiently.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8 max-w-6xl mx-auto">
            <div className="group bg-card border rounded-xl p-8 hover:shadow-lg transition-all duration-300">
              <div className="w-14 h-14 bg-indigo-50 dark:bg-indigo-950 rounded-xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                <Brain className="h-7 w-7 text-indigo-600 dark:text-indigo-400" />
              </div>
              <h3 className="text-xl font-semibold mb-3">AI-Powered Plans</h3>
              <p className="text-muted-foreground leading-relaxed">
                Get personalized workout and diet plans generated by advanced AI based on your goals, 
                preferences, and fitness level.
              </p>
            </div>

            <div className="group bg-card border rounded-xl p-8 hover:shadow-lg transition-all duration-300">
              <div className="w-14 h-14 bg-emerald-50 dark:bg-emerald-950 rounded-xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                <TrendingUp className="h-7 w-7 text-emerald-600 dark:text-emerald-400" />
              </div>
              <h3 className="text-xl font-semibold mb-3">Progress Tracking</h3>
              <p className="text-muted-foreground leading-relaxed">
                Monitor your fitness journey with detailed analytics, progress photos, and achievement 
                milestones to stay motivated.
              </p>
            </div>

            <div className="group bg-card border rounded-xl p-8 hover:shadow-lg transition-all duration-300">
              <div className="w-14 h-14 bg-amber-50 dark:bg-amber-950 rounded-xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                <Users className="h-7 w-7 text-amber-600 dark:text-amber-400" />
              </div>
              <h3 className="text-xl font-semibold mb-3">Expert Guidance</h3>
              <p className="text-muted-foreground leading-relaxed">
                Connect with certified trainers for personalized guidance and professional plan 
                customization tailored to your needs.
              </p>
            </div>
          </div>
        </div>

        {/* CTA Section */}
        <div className="container mx-auto px-4 py-20">
          <div className="bg-gradient-to-r from-indigo-50 via-emerald-50 to-amber-50 dark:from-indigo-950/30 dark:via-emerald-950/30 dark:to-amber-950/30 rounded-2xl p-12 text-center border">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Ready to Transform Your Life?</h2>
            <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
              Join thousands of users who have already achieved their fitness goals with Flexora.
            </p>
            <Link href="/auth">
              <Button size="lg" className="text-lg px-8 py-6">
                Get Started for Free
                <Apple className="ml-2 h-5 w-5" />
              </Button>
            </Link>
          </div>
        </div>

        {/* Footer */}
        <footer className="border-t bg-muted/30 py-12">
          <div className="container mx-auto px-4 text-center">
            <div className="flex items-center justify-center gap-2 mb-4">
              <Dumbbell className="h-6 w-6 text-primary" />
              <span className="text-lg font-semibold">Flexora</span>
            </div>
            <p className="text-muted-foreground">
              Your AI-powered personal fitness companion
            </p>
          </div>
        </footer>
      </div>
    )
  }

  // Redirect authenticated users to dashboard
  if (typeof window !== 'undefined') {
    window.location.href = '/dashboard'
  }
  
  return null
}
